In [1]:
import numpy as np


In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
b = np.array([[1,2,3],[1,4,6]])
print(b)

[[1 2 3]
 [1 4 6]]


In [7]:
#get dimension
a.ndim

1

In [8]:
#to get shape
b.shape

(2, 3)

In [9]:
#get data type
a.dtype

dtype('int32')

In [10]:
#get size
a.itemsize
#its the memory size of each element

4

In [11]:
a.size
#its the size of the array

3

In [14]:
a = np.array([[1,2,3,4,5,4],[2,3,4,5,6,7]])
print(a[0,2])

3


In [15]:
#get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 4])

In [16]:
#get a specific column
a[:,4]

array([5, 6])

In [18]:
#little more fancy [startindex:end index:stepsize]
a[0,1:-1:2]

array([2, 4])

In [19]:
#3d example
b = np.array([[[1,2],[3,4]],[[4,5],[3,4]]])
b

array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [3, 4]]])

In [22]:
#all zeros matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [24]:
#any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [25]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4]])

In [26]:
np.zeros_like(a)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [27]:
np.random.rand(4,3,2)

array([[[0.63291631, 0.80204012],
        [0.44951971, 0.93075753],
        [0.85564089, 0.87366733]],

       [[0.49995296, 0.56506761],
        [0.12111026, 0.08274465],
        [0.08261803, 0.09730454]],

       [[0.76696198, 0.96632653],
        [0.21986337, 0.92586796],
        [0.70247926, 0.74760578]],

       [[0.97990911, 0.75768138],
        [0.63841412, 0.94828653],
        [0.2195754 , 0.0315821 ]]])

In [30]:
np.random.random_sample(a.shape)

array([[0.12710583, 0.01634117, 0.99659188, 0.98631932, 0.66042963,
        0.60825776],
       [0.98014608, 0.61606496, 0.87735291, 0.12442457, 0.88438217,
        0.14872573]])

In [33]:
#random integer numbers
np.random.randint(4,8,size =(3,3))

array([[7, 5, 6],
       [6, 7, 6],
       [5, 4, 4]])

In [34]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
# repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


mathematics in numpy


In [40]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [41]:
a*2

array([2, 4, 6, 8])

In [42]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [43]:
a**2

array([ 1,  4,  9, 16])

In [44]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [46]:
a = np.ones((2,3))
b = np.full((3,2),2)
#multiply the elments of the arrays parallelly
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [47]:
#find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

statastics


In [48]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
np.min(arr)

1

In [50]:
np.max(arr,axis=0)

array([4, 5, 6])

In [51]:
np.min(arr,axis = 1)

array([1, 4])

In [52]:
np.sum(arr,axis=0)

array([5, 7, 9])

Reorganising arrays

In [53]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
after

[[1 2 3 4]
 [5 6 7 8]]


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [56]:
#vertical stacking of vectors
v1 = np.array([1,2,3,4])
v2 = np.array([4,5,6,7])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [1, 2, 3, 4],
       [4, 5, 6, 7]])

In [57]:
#horizantal stacking
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

Load data from file
